services:
  mh_web:
    build:
      context: .
      dockerfile: build/nginx/nginx.dockerfile
    ports:
      - '8081:80'
    volumes:
      - ./front:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mh_php
      - mh_mysql
    networks:
      - mh_network

  mh_php:
    build:
      context: .
      dockerfile: front/php.dockerfile
    volumes:
      - ./front:/var/www/html:cached
    networks:
      - mh_network
    links:
      - mh_mysql

  mh_mysql:
    image: mysql:8.0
    env_file:
      - ./env/mysql.env
    volumes:
      - data-mysql:/var/lib/mysql:rw
    ports:
      - 3388:3306
    networks:
      - mh_network

volumes:
  data-mysql:
    driver: local
networks:
  mh_network: